name = "Log2file"
uuid = "9348bb98-452d-4fd0-bebd-231ec7952d68"
authors = ["xuestrange <xjz1cumt@163.com> and contributors"]
version = "1.0.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
